{
 "title": "Cicis Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Cicis Process 1 Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"cicis-cicis-process-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cicis Process 2 Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"cicis-cicis-process-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "CICIS Process 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Message queue size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cicis_message_queue_size{container=\"cicis-process-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total processed messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "cicis_processed_messages{container=\"cicis-process-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CICIS Process 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Message queue size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cicis_message_queue_size{container=\"cicis-process-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total processed messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "cicis_processed_messages{container=\"cicis-process-2\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}