apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cmmc-service-monitor
  labels:
    name: prometheus
    release: prometheus
    app.kubernetes.io/instance: prometheus
spec:
  selector:
    matchLabels:
      operated-prometheus: "true"
  namespaceSelector:
    any: true
  endpoints:
    - port: http